<?php

namespace Blog\Twig;

use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

class AssetExtention extends AbstractExtension
{
    public function getFunctions()
    {
        return [
            new TwigFunction('asset_url', [$this, 'getAssetUrl'])
        ]; // TODO: Change the autogenerated stub
    }

    public function getAssetUrl(string $path): string
    {
        return 'http://blog.loc.php/' . $path;
    }
}